package:
  name: q2-cutadapt
  version: {{ PLUGIN_VERSION }}
source:
  path: ..
build:
  script: make install
requirements:
  host:
  - python {{ python }}
  - setuptools
  - versioningit
  - wheel
  run:
  - python {{ python }}
  - cutadapt {{ cutadapt }}
  - pigz
  - pandas {{ pandas }}
  - numpy
  - qiime2 >={{ qiime2 }}
  - q2-types >={{ q2_types }}
  build:
  - python {{ python }}
  - setuptools
  - versioningit
test:
  requires:
  - qiime2 >={{ qiime2 }}
  - q2-types >={{ q2_types }}
  - pytest
  imports:
  - q2_cutadapt
  - qiime2.plugins.cutadapt
  commands:
  - py.test --pyargs q2_cutadapt
about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
